{
 "title": "Blackbox Exporter",
 "description": "Blackbox exporter HTTP prober dashboard",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(probe_success,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$instance\"} == 0)"
    }
   ]
  },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "Instance status percentage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$instance\"} == 1)",
     "legendFormat": "Success status instance"
    },
    {
     "expr": "count(probe_success{instance=~\"$instance\"} == 0)",
     "legendFormat": "Failed status instance"
    }
   ]
  },
  {
   "title": "Expired in less than 30 days",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{instance=~\"$instance\"} - time() < (3600 * 24 * 30)"
    }
   ]
  },
  {
   "title": "Response code change record",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }, "repeat": "instance" },
  {
   "title": "HTTP Probe Phases Duration",
   "type": "timeseries",
   "description": "Duration of http request by phase, summed over all redirects",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  }
 ]
}