{
 "title": "Domain Expiration Overview",
 "description": "For more information, please visit https://github.com/zifter/helm-charts/tree/main/charts/domain-exporter",
 "tags": [
  "domain",
  "prometheus",
  "overview"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Overview: Will expire soon in Days",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (domain) (60 >= domain_expiry_days >= 0)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  {
   "title": "Overview: Failed to detect expiration time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min by (domain) (domain_probe_success==0)",
     "legendFormat": "{{domain}}"
    }
   ]
  },
  { "title": "All domains", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "All domains: Expiration in Weeks",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (domain) (domain_expiry_days)",
     "legendFormat": "{{domain}}"
    }
   ]
  }
 ]
}