{
 "title": "K8s-Deployments",
 "description": "Monitors Kubernetes cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "deployment",
    "query": {
     "query": "label_values(kube_deployment_metadata_generation{namespace=~\"$namespace\"}, deployment)"
    }
   },
   {
    "name": "statefulset",
    "label": "StatefulSet",
    "query": {
     "query": "label_values(kube_statefulset_metadata_generation{namespace=~\"$namespace\"},statefulset)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", created_by_name=~\"$deployment-\\\\w{5,10}\"}, pod)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_labels, label_kubernetes_io_hostname)"
    }
   },
   {
    "name": "interval",
    "query": "5m,10m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "deployment utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment  memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"${pod:regex}\",image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_pod_container_resource_requests{pod=~\"${pod:regex}\",resource=\"memory\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployment CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[5m])) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",pod=~\"${pod:regex}\",resource=\"cpu\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Per Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"${pod:regex}\",image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Usage per Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (max (sum (container_memory_working_set_bytes{pod=~\"${pod:regex}\",image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod ))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested Per Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{pod=~\"${pod:regex}\",resource=\"memory\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",  namespace=~\"$namespace\", pod=~\"${pod:regex}\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Usage per Pod",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time (max( sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\", pod=~\"${pod:regex}\"}[5m])) by (pod)) [$__range:] )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested  Per Deployment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{pod=~\"${pod:regex}\",resource=\"cpu\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "namespace utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Namespace memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$namespace\"}) / sum (kube_pod_container_resource_requests{namespace=~\"$namespace\", resource=\"memory\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespace CPU usage (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"$namespace\"}[5m])) / sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"cpu\"})  * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Usage  per Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum (container_memory_working_set_bytes{image!=\"\",kubernetes_io_hostname=~\"^$Node$\",namespace=~\"$namespace\"})[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"cron.*\",resource=\"memory\"}) +  (sum (min by (container) (kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"cron.*\",resource=\"memory\"})) or vector(0) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Usage per Namespace",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", namespace=~\"$namespace\"}[5m]))[$__range:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_pod_container_resource_requests{namespace=~\"$namespace\",pod!~\"cron.*\",resource=\"cpu\"}) +  (sum (min by (container) (kube_pod_container_resource_requests{namespace=~\"$namespace\",container=~\"cron.*\",resource=\"cpu\"})) or vector(0) )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Pods CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",kubernetes_io_hostname=~\"^$Node$\", pod=~\"${pod:regex}\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"${pod:regex}\",image!=\"\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"${deployment}\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Pods network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\", pod=~\"${pod:regex}\"}[5m])) by (pod)",
     "legendFormat": "-> {{ pod }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^.*\",kubernetes_io_hostname=~\"^$Node$\", pod=~\"${pod:regex}\"}[5m])) by (pod)",
     "legendFormat": "<- {{ pod }}"
    }
   ]
  },
  {
   "title": "Containers CPU usage (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"${pod:regex}\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (kubernetes_io_hostname, name, image, container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"${pod:regex}\",image!=\"\",name!~\"^k8s_.*\",kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (kubernetes_io_hostname, name, image, container, pod)",
     "legendFormat": "pod: {{ pod }} | {{ container }}"
    }
   ]
  },
  {
   "title": "Containers network I/O (5m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",pod=~\"${pod:regex}\", kubernetes_io_hostname=~\"^$Node$\"}[5m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "<- docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    },
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",pod=~\"${pod:regex}\", kubernetes_io_hostname=~\"^$Node$\",}[5m])) by (kubernetes_io_hostname, name, image)",
     "legendFormat": "-> docker: {{ kubernetes_io_hostname }} | {{ image }} ({{ name }})"
    }
   ]
  }
 ]
}