{
 "title": "Kubernetes: POD Overview",
 "tags": [
  "kubernetes",
  "pods"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\"},pod)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$namespace\", pod=~\"$pod\"},container)"
    }
   }
  ]
 },
 "panels": [
  { "title": "POD Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "POD Count (Namespace)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Pod Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg(kube_pod_status_phase{namespace=~\"$namespace\",pod=~\"$pod\"}) by(namespace, pod, phase)) by(phase,pod)",
     "legendFormat": "{{pod}} - {{ phase }}"
    }
   ]
  },
  {
   "title": "Pod Restart",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "POD Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU(Total all selected pod)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\",container=~\"$container\",image!=\"\"}[2m]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container,pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[30s]))",
     "legendFormat": "Current: {{ pod }} - {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}",
     "legendFormat": "Request: {{ pod }}  - {{container}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}",
     "legendFormat": "Limit: {{ pod }} - {{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (pod, container)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[1m]))  / avg(kube_pod_container_resource_requests{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}) by (pod, container) * 100",
     "legendFormat": "Requests: {{ pod }} - {{container}}"
    },
    {
     "expr": "sum by (pod, container)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container=~\"$container\", container!=\"POD\", image!=\"\"}[1m]))  / avg(kube_pod_container_resource_limits{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",unit=\"core\"}) by (pod, container) * 100",
     "legendFormat": "Limits: {{ pod }} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory(Total all selected pod)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"$namespace\", pod=~\"$pod\",container=~\"$container\", container!=\"POD\", container!=\"\",image!=\"\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by(pod, container) (container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "Current: {{ pod }} - {{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_limits{pod=~\"$pod\", unit=\"byte\" , container=~\"$container\", container!=\"POD\",container!=\"\"}) by (pod, container)",
     "legendFormat": "Limits: {{pod}} - {{container}}"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{pod=~\"$pod\", unit=\"byte\" , container=~\"$container\", container!=\"POD\",container!=\"\"}) by (pod, container)",
     "legendFormat": "Requests: {{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",container!=\"\",image!=\"\"}) by (pod, container)/ avg(kube_pod_container_resource_requests{pod=~\"$pod\", unit=\"byte\" , container=~\"$container\", container!=\"POD\",container!=\"\"}) by (pod, container) * 100",
     "legendFormat": "Requests(%) : {{pod}} - {{container}}"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"$pod\", container=~\"$container\", container!=\"POD\",container!=\"\",image!=\"\"}) by (pod, container)/ avg(kube_pod_container_resource_limits{pod=~\"$pod\", unit=\"byte\" , container=~\"$container\", container!=\"POD\",container!=\"\"}) by (pod, container) * 100",
     "legendFormat": "Limits(%) : {{pod}} - {{container}}"
    }
   ]
  },
  {
   "title": "Network RX/TX Total (bytes/sec)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) + sum(rate(container_network_receive_bytes_total{namespace=~\"$namespace\",pod=~\"$pod\"}[5m])) "
    }
   ]
  },
  {
   "title": "POD Network",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "TX : {{ pod_name }}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{pod=~\"$pod\",interface=~\"eth0|ens.*\"}[5m])",
     "legendFormat": "RX : {{ pod_name }}"
    }
   ]
  }
 ]
}