{
 "title": "Kubernetes Statefulset Metrics",
 "description": "Simple dashboard for observing your Kubernetes Statefulset CPU and Memory usage.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DataSource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_statefulset_status_observed_generation,namespace)"
    }
   },
   {
    "name": "statefulset",
    "query": {
     "query": "label_values(kube_statefulset_status_replicas{namespace=\"$namespace\"},statefulset)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory Usage Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage StatefulSet Wise",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - request"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=~\"$statefulset.*\"}[$__rate_interval])) by (statefulset)",
     "legendFormat": "$statefulset  - usage"
    }
   ]
  },
  {
   "title": "Memory Usage StatefulSet Wise",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - request"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "$statefulset  - usage"
    }
   ]
  },
  {
   "title": "CPU Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Request per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Limit per Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$statefulset.*\"}) by (statefulset)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods Resource Usage - $pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "pod" },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "All pods CPU usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod=~\"$pod\", container!=\"POD\", image!=\"\"}[1m]))",
     "legendFormat": "$pod  - usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "All pods memory usage combined for selected statefulset",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod - limit"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\", pod=~\"$pod.*\"}) by (pod)",
     "legendFormat": "$pod  - request"
    },
    {
     "expr": "avg by(pod) (container_memory_working_set_bytes{pod=~\"$pod\", container!=\"POD\",container!=\"\",image!=\"\"})",
     "legendFormat": "$pod  - Current"
    }
   ]
  }
 ]
}